const chapterDetails1 = [
  {
    id: 101280,
    STATUS: null,
    ANSWER_DATA: "<p>b. nutritients</p>\r\n",
    CATEGORY_ID: 10983,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>The components of food are necessary for our body and are called _____________ .</p>\r\n\r\n<p>a. symbiotics&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;b. nutritients&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;c. saprophytics&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;d. parasites</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Tick ✓ the correct answer. (MCQs)",
  },
  {
    id: 101281,
    STATUS: null,
    ANSWER_DATA: "<p>a. plants</p>\r\n",
    CATEGORY_ID: 10983,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>All humans and animals are directly or indirectly dependent on _____________ .</p>\r\n\r\n<p>a. plants&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;b. animals&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;c. humans&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;d. all of them</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Tick ✓ the correct answer. (MCQs)",
  },
  {
    id: 101282,
    STATUS: null,
    ANSWER_DATA: "<p>&nbsp;b. stoma</p>\r\n",
    CATEGORY_ID: 10983,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>The_____________ is surrounded by two guard cells and several epidermal cells.</p>\r\n\r\n<p>a. pore&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;b. stoma&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;c. cell d. tissue</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Tick ✓ the correct answer. (MCQs)",
  },
  {
    id: 101283,
    STATUS: null,
    ANSWER_DATA: "<p>c. Chlorophyll</p>\r\n",
    CATEGORY_ID: 10983,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ is present mostly in the green leaves of the plants.</p>\r\n\r\n<p>a. Glucose&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b. Cellulose&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c. Chlorophyll&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; d. Starch14</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Tick ✓ the correct answer. (MCQs)",
  },
  {
    id: 101284,
    STATUS: null,
    ANSWER_DATA: "<p>a. Rafflesia</p>\r\n",
    CATEGORY_ID: 10983,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ , a parasitic plant, is found in the forests of Malaysia.</p>\r\n\r\n<p>a. Rafflesia&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; b. Lichen&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c. Drosera&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; d. Cuscuta</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Tick ✓ the correct answer. (MCQs)",
  },
  {
    id: 101285,
    STATUS: null,
    ANSWER_DATA: "<p>c. Photosynthesis</p>\r\n",
    CATEGORY_ID: 10983,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ is the process that takes place in the presence of sunlight.</p>\r\n\r\n<p>a. Transpiration&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;b. Replenishment&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;c. Photosynthesis&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;d. Evaporation</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Tick ✓ the correct answer. (MCQs)",
  },
];
const chapterDetails2 = [
  {
    id: 101286,
    STATUS: null,
    ANSWER_DATA: "<p>autotrophic</p>\r\n",
    CATEGORY_ID: 38,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>All green plants and certain bacteria belong to _____________ nutrition group.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Fill in the blanks using the suitable words.",
  },
  {
    id: 101287,
    STATUS: null,
    ANSWER_DATA: "<p>photosynthesis</p>\r\n",
    CATEGORY_ID: 38,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ provides the basic energy source for almost all organisms.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Fill in the blanks using the suitable words.",
  },
  {
    id: 101288,
    STATUS: null,
    ANSWER_DATA: "<p>stomata</p>\r\n",
    CATEGORY_ID: 38,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>The guard cells regulate the opening and closing of the _____________ .</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Fill in the blanks using the suitable words.",
  },
  {
    id: 101289,
    STATUS: null,
    ANSWER_DATA: "<p>Cuscuta</p>\r\n",
    CATEGORY_ID: 38,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ is a pale yellow twining plant often seen on tree tops.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Fill in the blanks using the suitable words.",
  },
  {
    id: 101290,
    STATUS: null,
    ANSWER_DATA: "<p>Rafflesia</p>\r\n",
    CATEGORY_ID: 38,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ grows up to 1 metre wide and weighs about 10 kgs.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Fill in the blanks using the suitable words.",
  },
  {
    id: 101291,
    STATUS: null,
    ANSWER_DATA: "<p>Mistletoe</p>\r\n",
    CATEGORY_ID: 38,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>_____________ has green leaves to carry out photosynthesis.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Fill in the blanks using the suitable words.",
  },
];
const chapterDetails3 = [
  {
    id: 101292,
    STATUS: null,
    ANSWER_DATA:
      "<p>Carbohydrates, proteins, fats, vitamins and minerals.</p>\r\n",
    CATEGORY_ID: 11112,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>What are the components of food?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in brief.",
  },
  {
    id: 101293,
    STATUS: null,
    ANSWER_DATA:
      "<p>Nutrition is the process of taking &hellip;...&hellip;&hellip;. by the body.</p>\r\n",
    CATEGORY_ID: 11112,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>What do you mean by nutrition?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in brief.",
  },
  {
    id: 101294,
    STATUS: null,
    ANSWER_DATA: "<p>for the proper growth of our body.</p>\r\n",
    CATEGORY_ID: 11112,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>Why is nutrition necessary for us?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in brief.",
  },
  {
    id: 101295,
    STATUS: null,
    ANSWER_DATA:
      "<p>Organisms that can synthesise &hellip;...&hellip;..&hellip;.... are called autotrophs.</p>\r\n",
    CATEGORY_ID: 11112,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>What do you understand by autotrophs?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in brief.",
  },
  {
    id: 101296,
    STATUS: null,
    ANSWER_DATA:
      "<p>The mode of nutrition &hellip;...&hellip;..........&hellip; saprotrophic nutrition.</p>\r\n",
    CATEGORY_ID: 11112,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>Define the term &lsquo;saprotrophic nutrition&rsquo;.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in brief.",
  },
  {
    id: 101297,
    STATUS: null,
    ANSWER_DATA: "<p>Carbon dioxide, water, chlorophyll and sunlight.</p>\r\n",
    CATEGORY_ID: 11112,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>What are the essential factors required for the photosynthesis?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in brief.",
  },
];
const chapterDetails4 = [
  {
    id: 101298,
    STATUS: null,
    ANSWER_DATA:
      "<p>Organisms that can synthesise &hellip;...&hellip;&hellip;. bacteria belong to this group.</p>\r\n",
    CATEGORY_ID: 27,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>What is autotrophic mode of nutrition? Describe it.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in detail.",
  },
  {
    id: 101299,
    STATUS: null,
    ANSWER_DATA:
      "<p>Organisms that can obtain their energy &hellip;...&hellip;...&hellip;. called heterotrophic nutrition.</p>\r\n",
    CATEGORY_ID: 27,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>What is heterotrophic mode of nutrition? Describe it.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in detail.",
  },
  {
    id: 101300,
    STATUS: null,
    ANSWER_DATA:
      "<p>Photosynthesis is the process ...&hellip;.....&hellip; most organisms depend.</p>\r\n",
    CATEGORY_ID: 27,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>Describe the process of photosynthesis.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in detail.",
  },
  {
    id: 101301,
    STATUS: null,
    ANSWER_DATA:
      "<p>Plants absorb the mineral nutrients, &hellip;...&hellip;....&hellip;. to enrich the soil.</p>\r\n",
    CATEGORY_ID: 27,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>Why do farmers add nitrogenous fertilisers to the soil?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in detail.",
  },
  {
    id: 101302,
    STATUS: null,
    ANSWER_DATA:
      "<p>Plants which use saprotrophic mode of &hellip;..&hellip;....&hellip;. utrients from it.</p>\r\n",
    CATEGORY_ID: 27,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>What do you understand by saprotrophs? Explain.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in detail.",
  },
  {
    id: 101303,
    STATUS: null,
    ANSWER_DATA:
      "<p>There is a bacterium called Rhizobium, which lives in &hellip;...&hellip;.... addition of nitrogenous fertilisers.</p>\r\n",
    CATEGORY_ID: 27,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA: "<p>How do nutrients get replenished in the soil?</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Answer the following questions in detail.",
  },
];
const chapterDetails5 = [
  {
    id: 101304,
    STATUS: null,
    ANSWER_DATA: "<p>F</p>\r\n",
    CATEGORY_ID: 11086,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>All humans and animals are directly or indirectly dependent on human resources.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Write ‘T’ for true and ‘F’ for false statements.",
  },
  {
    id: 101305,
    STATUS: null,
    ANSWER_DATA: "<p>T</p>\r\n",
    CATEGORY_ID: 11086,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>Photosynthesis provides the basic energy source for almost all organisms.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Write ‘T’ for true and ‘F’ for false statements.",
  },
  {
    id: 101306,
    STATUS: null,
    ANSWER_DATA: "<p>T</p>\r\n",
    CATEGORY_ID: 11086,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>An extremely important by-product of photosynthesis is oxygen, on which most organisms depend.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Write ‘T’ for true and ‘F’ for false statements.",
  },
  {
    id: 101307,
    STATUS: null,
    ANSWER_DATA: "<p>F&nbsp;</p>\r\n",
    CATEGORY_ID: 11086,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>Chloroplasts present in the plant cell contain the yellow pigment called chlorophyll.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Write ‘T’ for true and ‘F’ for false statements.",
  },
  {
    id: 101308,
    STATUS: null,
    ANSWER_DATA: "<p>T</p>\r\n",
    CATEGORY_ID: 11086,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>During photosynthesis process, the solar energy is converted into chemical energy of food.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Write ‘T’ for true and ‘F’ for false statements.",
  },
  {
    id: 101309,
    STATUS: null,
    ANSWER_DATA: "<p>T</p>\r\n",
    CATEGORY_ID: 11086,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>Plants which use saprotrophic mode of nutrition are called saprotrophs.</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Write ‘T’ for true and ‘F’ for false statements.",
  },
];
const chapterDetails6 = [
  {
    id: 101278,
    STATUS: null,
    ANSWER_DATA: "<p>1. c 2. d 3. b 4. f 5. a 6. e</p>\r\n",
    CATEGORY_ID: 17,
    CHAPTER_ID: 3255,
    FILE_ID: 1,
    QUESTION_DATA:
      "<p>COLUMN (A)&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;COLUMN (B)</p>\r\n\r\n<p>1. Autotrophic nutrition&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; a. tiny structures present in the plant cell</p>\r\n\r\n<p>2. Photosynthesis&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;b.present in the underside of the leaves</p>\r\n\r\n<p>3. Stomata&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; c. organisms that can prepare their own food</p>\r\n\r\n<p>4. Guard cells&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; d. the process of making food using sunlight</p>\r\n\r\n<p>5. Chloroplasts&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; e. Venus flytrap and Drosera</p>\r\n\r\n<p>6. Insectivorous plants&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;f. regulate the opening and closing of the stomata</p>\r\n",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "Match the following.",
  },
];

export const chapterDetailsData = [
  chapterDetails1,
  chapterDetails2,
  chapterDetails3,
  chapterDetails4,
  chapterDetails5,
  chapterDetails6,
].flat();
