const chapters = [
  {
    id: 9211,
    STATUS: null,
    BOOK_ID: 493,
    NAME: "Living and Non-Living Things",
  },
  {
    id: 9212,
    STATUS: null,
    BOOK_ID: 493,
    NAME: "Parts of a Plant",
  },
  {
    id: 9213,
    STATUS: null,
    BOOK_ID: 493,
    NAME: "Eating Habits of Animals",
  },
  {
    id: 9214,
    STATUS: null,
    BOOK_ID: 493,
    NAME: "Birds",
  },
  {
    id: 9215,
    STATUS: null,
    BOOK_ID: 493,
    NAME: "Soil",
  },
  {
    id: 9216,
    STATUS: null,
    BOOK_ID: 493,
    NAME: "States of Matter",
  },
];

const questionCategories = [
  {
    id: 19736,
    category_name: "\tAnswer the following questions.",
  },
  {
    id: 20587,
    category_name: "\tFill in the blanks.",
  },
  {
    id: 22472,
    category_name: "\tTick (?) the right option. (MCQs)",
  },
  {
    id: 22473,
    category_name: "\tTick (?) the correct and cross (X) the wrong statements.",
  },
];

const questionOfCategoryOne = [
  {
    id: 217200,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 20587,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tLiving things need food and water to ________ alive. </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tFill in the blanks.",
  },
  {
    id: 217201,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 20587,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tTigers, lions, jackals, etc. eat _____________. </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tFill in the blanks.",
  },
  {
    id: 217202,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 20587,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tAnimals depend directly or indirectly on _________ for food. </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tFill in the blanks.",
  },
  {
    id: 217203,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 20587,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tNon-living things do not respond to changes in the __________. </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tFill in the blanks.",
  },
  {
    id: 217204,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 20587,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tPlants breathe through_____________. </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tFill in the blanks.",
  },
];

const questionOfCategoryTwo = [
  {
    id: 217205,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22472,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tLiving things need food to ______________.</p><p>a. tall \tb. energy c. grow</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the right option. (MCQs)",
  },
  {
    id: 217206,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22472,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>Which of these is a non-living thing? </p><p>\ta. Rock  \tb. Tree c. Dog </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the right option. (MCQs)",
  },
  {
    id: 217207,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22472,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>Which of these is a natural non-living thing? </p><p>\ta. Computer\tb. Water c. Paper </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the right option. (MCQs)",
  },
  {
    id: 217208,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22472,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>A puppy grows into a _________. </p><p>a. camel \tb. dog c. kitten</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the right option. (MCQs)",
  },
  {
    id: 217209,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22472,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tHuman beings breathe through___________. </p><p>a. gills \tb. fins \tc. nose </p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the right option. (MCQs)",
  },
];

const questionOfCategoryThree = [
  {
    id: 217210,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22473,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tPlants, animals and human beings are living things.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the correct and cross (X) the wrong statements.",
  },
  {
    id: 217211,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22473,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>All living things grow taller and wider.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the correct and cross (X) the wrong statements.",
  },
  {
    id: 217212,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22473,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tAll living things have a life cycle.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the correct and cross (X) the wrong statements.",
  },
  {
    id: 217213,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22473,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tNon-living things can die early.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the correct and cross (X) the wrong statements.",
  },
  {
    id: 217214,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 22473,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tLiving and non-living things are made up of some materials.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tTick (?) the correct and cross (X) the wrong statements.",
  },
];

const questionOfCategoryFour = [
  {
    id: 217195,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 19736,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>What are living things?</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tAnswer the following questions.",
  },
  {
    id: 217196,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 19736,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tHow do living things move?</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tAnswer the following questions.",
  },
  {
    id: 217197,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 19736,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tHow do living things grow?</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tAnswer the following questions.",
  },
  {
    id: 217198,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 19736,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA: "<p>\tExplain the life cycle of a mosquito.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tAnswer the following questions.",
  },
  {
    id: 217199,
    STATUS: null,
    ANSWER_DATA: "",
    CATEGORY_ID: 19736,
    CHAPTER_ID: 9211,
    FILE_ID: 3006,
    QUESTION_DATA:
      "<p>\tWrite three examples each of natural and man-made things.</p>",
    REASON: null,
    REMARKS: null,
    STAGE: null,
    type: null,
    category_name: "\tAnswer the following questions.",
  },
];

export {
  chapters,
  questionCategories,
  questionOfCategoryOne,
  questionOfCategoryTwo,
  questionOfCategoryThree,
  questionOfCategoryFour,
};
