/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrintImport } from './routes/print'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'

// Create Virtual Routes

const ForgotPasswordLazyImport = createFileRoute('/forgot-password')()
const AuthIndexLazyImport = createFileRoute('/_auth/')()
const AuthUsersLazyImport = createFileRoute('/_auth/users')()
const AuthPreviewLazyImport = createFileRoute('/_auth/preview')()
const AuthExamTypeLazyImport = createFileRoute('/_auth/exam-type')()
const AuthAutoBuilderLazyImport = createFileRoute('/_auth/auto-builder')()
const AuthBuilderExamIdLazyImport = createFileRoute('/_auth/builder/$examId')()

// Create/Update Routes

const ForgotPasswordLazyRoute = ForgotPasswordLazyImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)

const PrintRoute = PrintImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/index.lazy').then((d) => d.Route))

const AuthUsersLazyRoute = AuthUsersLazyImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/users.lazy').then((d) => d.Route))

const AuthPreviewLazyRoute = AuthPreviewLazyImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/preview.lazy').then((d) => d.Route))

const AuthExamTypeLazyRoute = AuthExamTypeLazyImport.update({
  id: '/exam-type',
  path: '/exam-type',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/exam-type.lazy').then((d) => d.Route),
)

const AuthAutoBuilderLazyRoute = AuthAutoBuilderLazyImport.update({
  id: '/auto-builder',
  path: '/auto-builder',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/auto-builder.lazy').then((d) => d.Route),
)

const AuthBuilderExamIdLazyRoute = AuthBuilderExamIdLazyImport.update({
  id: '/builder/$examId',
  path: '/builder/$examId',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/builder.$examId.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/print': {
      id: '/print'
      path: '/print'
      fullPath: '/print'
      preLoaderRoute: typeof PrintImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/auto-builder': {
      id: '/_auth/auto-builder'
      path: '/auto-builder'
      fullPath: '/auto-builder'
      preLoaderRoute: typeof AuthAutoBuilderLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/exam-type': {
      id: '/_auth/exam-type'
      path: '/exam-type'
      fullPath: '/exam-type'
      preLoaderRoute: typeof AuthExamTypeLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/preview': {
      id: '/_auth/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthPreviewLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/builder/$examId': {
      id: '/_auth/builder/$examId'
      path: '/builder/$examId'
      fullPath: '/builder/$examId'
      preLoaderRoute: typeof AuthBuilderExamIdLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAutoBuilderLazyRoute: typeof AuthAutoBuilderLazyRoute
  AuthExamTypeLazyRoute: typeof AuthExamTypeLazyRoute
  AuthPreviewLazyRoute: typeof AuthPreviewLazyRoute
  AuthUsersLazyRoute: typeof AuthUsersLazyRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
  AuthBuilderExamIdLazyRoute: typeof AuthBuilderExamIdLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAutoBuilderLazyRoute: AuthAutoBuilderLazyRoute,
  AuthExamTypeLazyRoute: AuthExamTypeLazyRoute,
  AuthPreviewLazyRoute: AuthPreviewLazyRoute,
  AuthUsersLazyRoute: AuthUsersLazyRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
  AuthBuilderExamIdLazyRoute: AuthBuilderExamIdLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/print': typeof PrintRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/auto-builder': typeof AuthAutoBuilderLazyRoute
  '/exam-type': typeof AuthExamTypeLazyRoute
  '/preview': typeof AuthPreviewLazyRoute
  '/users': typeof AuthUsersLazyRoute
  '/': typeof AuthIndexLazyRoute
  '/builder/$examId': typeof AuthBuilderExamIdLazyRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/print': typeof PrintRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/auto-builder': typeof AuthAutoBuilderLazyRoute
  '/exam-type': typeof AuthExamTypeLazyRoute
  '/preview': typeof AuthPreviewLazyRoute
  '/users': typeof AuthUsersLazyRoute
  '/': typeof AuthIndexLazyRoute
  '/builder/$examId': typeof AuthBuilderExamIdLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/print': typeof PrintRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/_auth/auto-builder': typeof AuthAutoBuilderLazyRoute
  '/_auth/exam-type': typeof AuthExamTypeLazyRoute
  '/_auth/preview': typeof AuthPreviewLazyRoute
  '/_auth/users': typeof AuthUsersLazyRoute
  '/_auth/': typeof AuthIndexLazyRoute
  '/_auth/builder/$examId': typeof AuthBuilderExamIdLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/print'
    | '/forgot-password'
    | '/auto-builder'
    | '/exam-type'
    | '/preview'
    | '/users'
    | '/'
    | '/builder/$examId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/print'
    | '/forgot-password'
    | '/auto-builder'
    | '/exam-type'
    | '/preview'
    | '/users'
    | '/'
    | '/builder/$examId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/print'
    | '/forgot-password'
    | '/_auth/auto-builder'
    | '/_auth/exam-type'
    | '/_auth/preview'
    | '/_auth/users'
    | '/_auth/'
    | '/_auth/builder/$examId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrintRoute: typeof PrintRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PrintRoute: PrintRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/print",
        "/forgot-password"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/auto-builder",
        "/_auth/exam-type",
        "/_auth/preview",
        "/_auth/users",
        "/_auth/",
        "/_auth/builder/$examId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/print": {
      "filePath": "print.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.lazy.tsx"
    },
    "/_auth/auto-builder": {
      "filePath": "_auth/auto-builder.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/exam-type": {
      "filePath": "_auth/exam-type.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/preview": {
      "filePath": "_auth/preview.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/users": {
      "filePath": "_auth/users.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/builder/$examId": {
      "filePath": "_auth/builder.$examId.lazy.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
