/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'

// Create Virtual Routes

const ForgotPasswordLazyImport = createFileRoute('/forgot-password')()
const AuthIndexLazyImport = createFileRoute('/_auth/')()
const AuthPreviewLazyImport = createFileRoute('/_auth/preview')()
const AuthExamTypeLazyImport = createFileRoute('/_auth/exam-type')()
const AuthBuilderLazyImport = createFileRoute('/_auth/builder')()

// Create/Update Routes

const ForgotPasswordLazyRoute = ForgotPasswordLazyImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/forgot-password.lazy').then((d) => d.Route),
)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexLazyRoute = AuthIndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/index.lazy').then((d) => d.Route))

const AuthPreviewLazyRoute = AuthPreviewLazyImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/preview.lazy').then((d) => d.Route))

const AuthExamTypeLazyRoute = AuthExamTypeLazyImport.update({
  id: '/exam-type',
  path: '/exam-type',
  getParentRoute: () => AuthRoute,
} as any).lazy(() =>
  import('./routes/_auth/exam-type.lazy').then((d) => d.Route),
)

const AuthBuilderLazyRoute = AuthBuilderLazyImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/builder.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordLazyImport
      parentRoute: typeof rootRoute
    }
    '/_auth/builder': {
      id: '/_auth/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof AuthBuilderLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/exam-type': {
      id: '/_auth/exam-type'
      path: '/exam-type'
      fullPath: '/exam-type'
      preLoaderRoute: typeof AuthExamTypeLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/preview': {
      id: '/_auth/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof AuthPreviewLazyImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexLazyImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthBuilderLazyRoute: typeof AuthBuilderLazyRoute
  AuthExamTypeLazyRoute: typeof AuthExamTypeLazyRoute
  AuthPreviewLazyRoute: typeof AuthPreviewLazyRoute
  AuthIndexLazyRoute: typeof AuthIndexLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBuilderLazyRoute: AuthBuilderLazyRoute,
  AuthExamTypeLazyRoute: AuthExamTypeLazyRoute,
  AuthPreviewLazyRoute: AuthPreviewLazyRoute,
  AuthIndexLazyRoute: AuthIndexLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/builder': typeof AuthBuilderLazyRoute
  '/exam-type': typeof AuthExamTypeLazyRoute
  '/preview': typeof AuthPreviewLazyRoute
  '/': typeof AuthIndexLazyRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/builder': typeof AuthBuilderLazyRoute
  '/exam-type': typeof AuthExamTypeLazyRoute
  '/preview': typeof AuthPreviewLazyRoute
  '/': typeof AuthIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/forgot-password': typeof ForgotPasswordLazyRoute
  '/_auth/builder': typeof AuthBuilderLazyRoute
  '/_auth/exam-type': typeof AuthExamTypeLazyRoute
  '/_auth/preview': typeof AuthPreviewLazyRoute
  '/_auth/': typeof AuthIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/forgot-password'
    | '/builder'
    | '/exam-type'
    | '/preview'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/forgot-password'
    | '/builder'
    | '/exam-type'
    | '/preview'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/forgot-password'
    | '/_auth/builder'
    | '/_auth/exam-type'
    | '/_auth/preview'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  ForgotPasswordLazyRoute: typeof ForgotPasswordLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  ForgotPasswordLazyRoute: ForgotPasswordLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/forgot-password"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/builder",
        "/_auth/exam-type",
        "/_auth/preview",
        "/_auth/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.lazy.tsx"
    },
    "/_auth/builder": {
      "filePath": "_auth/builder.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/exam-type": {
      "filePath": "_auth/exam-type.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/preview": {
      "filePath": "_auth/preview.lazy.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.lazy.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
